# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    container_name: docker_db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: docker_contact
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
    ports:
      - "3306:3306"
  web:
    image: php:7.4-apache
    container_name: docker_web
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "80:80"
    stdin_open: true
    tty: true